#!/bin/zsh

cd /mnt/cephfs
echo "Creating dirs and files"
mkdir -p {a,b}{1,2,3}/{c,d}{1,2,3}
for i in {a,b}{1,2,3}/{c,d}{1,2,3}/f{1,2,3}; do
  dd if=/dev/zero of=$i$(date +%N) bs=$((($(date +%N)) % 50))M count=1
done
