#!/bin/zsh

obj=/root/o

function easy_mode {
  dd if=/dev/zero of=${obj}0 bs=16K count=1
  dd if=/dev/zero of=${obj}1 bs=32K count=1
  dd if=/dev/zero of=${obj}2 bs=64K count=1
  dd if=/dev/zero of=${obj}3 bs=128K count=1
  dd if=/dev/zero of=${obj}4 bs=256K count=1
  dd if=/dev/zero of=${obj}5 bs=512K count=1
  dd if=/dev/zero of=${obj}6 bs=1M count=1
  dd if=/dev/zero of=${obj}7 bs=2M count=1
}

function normal_mode {
  dd if=/dev/zero of=${obj}0 bs=512K count=1
  dd if=/dev/zero of=${obj}1 bs=1M count=1
  dd if=/dev/zero of=${obj}2 bs=1536K count=1
  dd if=/dev/zero of=${obj}3 bs=2560K count=1
  dd if=/dev/zero of=${obj}4 bs=4M count=1
  dd if=/dev/zero of=${obj}5 bs=6656K count=1
  dd if=/dev/zero of=${obj}6 bs=10752K count=1
  dd if=/dev/zero of=${obj}7 bs=17M count=1
}

function hard_mode {
  dd if=/dev/zero of=${obj}0 bs=2M count=1
  dd if=/dev/zero of=${obj}1 bs=4M count=1
  dd if=/dev/zero of=${obj}2 bs=8M count=1
  dd if=/dev/zero of=${obj}3 bs=16M count=1
  dd if=/dev/zero of=${obj}4 bs=32M count=1
  dd if=/dev/zero of=${obj}5 bs=64M count=1
  dd if=/dev/zero of=${obj}6 bs=128M count=1
  dd if=/dev/zero of=${obj}7 bs=256M count=1
}

# easy_mode
normal_mode
# hard_mode


function wPool {
  rados -p $1 put o$i $obj$((($(date +%N) + $i) % 8))
  i=$(($i+1))
}

function rPool {
  rados -p $1 ls | while read x; do
    if [ $((($(date +%N)) % 8)) -eq 0 ]; then
      rados -p $1 get $x /dev/zero
    fi
  done
}

function rwOnPool {
  #$1 = pool name
  for sth in {1..5}; do
    wPool $1 &
  done
  rPool $1 &
}

i=$(date +%N)
for sth in {1..100}; do
  ceph osd lspools | awk '{print $2}' | while read p; do
    rwOnPool $p &
    #sleep 1
  done
done
