#!/bin/bash
#set -e

#--------------------
# Spin up the cluster
#--------------------

cd /ceph/build
rm -rf /ceph/build/out/*
find /ceph/src -name \*.pyc -delete

RGW=1 MDS=1 MON=1 OSD=3  ../src/vstart.sh -d -n -x
ceph mgr module enable volumes

#--------------
# Configure RGW
#--------------

./bin/radosgw-admin user create --uid=dev --display-name=Developer --system

ceph dashboard set-rgw-api-user-id dev
ceph dashboard set-rgw-api-access-key `./bin/radosgw-admin user info --uid=dev | jq .keys[0].access_key | sed -e 's/^"//' -e 's/"$//'`
ceph dashboard set-rgw-api-secret-key `./bin/radosgw-admin user info --uid=dev | jq .keys[0].secret_key | sed -e 's/^"//' -e 's/"$//'`

#-----------------------------
# Add test pool to create RBDs
#-----------------------------

ceph osd pool create rbdPool 16
ceph osd pool application enable rbdPool rbd

#------------------------
# Dashboard configuration
#------------------------

# Connect to APIs
ceph dashboard set-grafana-api-url 'http://localhost:3000'
ceph dashboard set-prometheus-api-host 'http://localhost:9090'
ceph dashboard set-alertmanager-api-host 'http://localhost:9093'

# Development settings
ceph dashboard set-enable-browsable-api true
ceph dashboard set-audit-api-enabled true
# By setting the dashboard to a static port you don't have to rerun 'npm start' on every reload
ceph config set mgr mgr/dashboard/x/server_port 8383

#---------------------
# Starting mgr modules
#---------------------

ceph mgr module enable prometheus

reload-dashboard
# Only the first time you have to wait 10s if it's created it won't change
# But it will prevent to target 'null'
sleep 10
set-proxy
