#!/bin/bash
#set -e
export PATH=/scripts:$PATH:/ceph/build/bin

#--------------------
# Spin up the cluster
#--------------------

function spinUpCluster {
  cd /ceph/build
  rm -rf /ceph/build/out/*
  find /ceph/src -name \*.pyc -delete

  RGW=1 MGR=1 MDS=2 MON=1 OSD=3  ../src/vstart.sh -d -n -x
  ceph mgr module enable volumes
}

#--------------
# Configure RGW
#--------------

function confRgw {
  echo "rgw configuration"
  radosgw-admin user create --uid=dev --display-name=Developer --system
  ceph dashboard set-rgw-api-user-id dev
  ceph dashboard set-rgw-api-access-key `./bin/radosgw-admin user info --uid=dev | jq -r ".keys[0].access_key"`
  ceph dashboard set-rgw-api-secret-key `./bin/radosgw-admin user info --uid=dev | jq -r ".keys[0].secret_key"`
}

#-----------------------------
# Add test pool to create RBDs
#-----------------------------

function createRbdPool {
  echo "Create rbd pool"
  #rbd pool normal
  ceph osd pool create rbd.a 4
  ceph osd pool application enable rbd.a rbd
}

function createRbdWithCachePool {
  echo "Create rbd pool bonded with a cache pool"
  ceph osd pool create rbd.b.main 4
  ceph osd pool create rbd.b.cache 4
  ceph osd pool application enable rbd.b.cache rbd
  ceph osd tier add rbd.b.main rbd.b.cache
  ceph osd tier cache-mode rbd.b.cache writeback
  ceph osd tier set-overlay rbd.b.main rbd.b.cache
  ceph osd pool set rbd.b.cache hit_set_type bloom
}

function createCephFs {
  echo "Create an cephfs data and meta data pool"
  ceph osd pool create cephfs.b.data 32
  ceph osd pool create cephfs.b.meta 16
  ceph osd pool application enable cephfs.b.data cephfs # is not enforced yet
  ceph osd pool application enable cephfs.b.meta cephfs # is not enforced yet
  ceph fs flag set enable_multiple true
  ceph fs new cephfs.b cephfs.b.meta cephfs.b.data # bekommt den namen a am ende (vermutung weil auf mon a)
}

#------------------------
# Dashboard configuration
#------------------------
function dashboard {
  echo "dahboard configuration"

  echo "development settings"
  # Development settings
  ceph dashboard set-enable-browsable-api true
  ceph dashboard set-audit-api-enabled true
  ceph dashboard debug enable

  echo "set port"
  # By setting the dashboard to a static port you don't have to rerun 'npm start' on every reload
  ceph config set mgr mgr/dashboard/x/server_port 8382
  # only ssl port will be used - but I will set the native port two
  ceph config set mgr mgr/dashboard/x/ssl_server_port 8383
}

function dashboard_externals {
  echo "connect apis"
  # Connect to APIs
  ceph dashboard set-grafana-api-url 'http://localhost:3000'
  ceph dashboard set-prometheus-api-host 'http://localhost:9090'
  ceph dashboard set-alertmanager-api-host 'http://localhost:9093'

  echo "starting modules"
  ceph mgr module enable prometheus
}

#---------------------
# Starting mgr modules
#---------------------
function mgrModules {
  reload-dashboard
  # Only the first time you have to wait 10s if it's created it won't change
  # But it will prevent to target 'null'
  sleep 20
  set-proxy
}


#-------------
# Mount cephfs (only once)
#-------------

function mount_cephfs {
  if [ -z "$(ps | grep fuse | awk '{print $1}')" ]; then
    cd /ceph/build
    rm -r /mnt/cephfs
    mkdir /mnt/cephfs
    sleep 3
    ceph-fuse -d -f /mnt/cephfs &
    sleep 3
  fi
}

#--------------------------------
# Spin up cluster with everything
#--------------------------------
function holeCluster {
  spinUpCluster
  confRgw
  #createRbdPool
  #createRbdWithCachePool
  #createCephFs
  dashboard
  #dashboard_externals
  mgrModules
  mount_cephfs # Let's the manager go wild after some time
}

holeCluster
#addCephfsData # I reset my cluster to often
