#!/bin/zsh

cd /ceph/src/pybind/mgr/dashboard

# Unit tests
WITH_PYTHON2=OFF ./run-tox.sh
./run-frontend-unittests.sh

# Integration tests
#./run-frontend-e2e-tests.sh
#./run-backend-api-tests.sh

# Send coverage reports
./update-codecov.sh
